### ISSUE TITLE
Ubuntu 软件相关

### ISSUE THREAD

**Issue by jetxa** [jetxa/jetxa.github.io#29]

**Comment by jetxa** [comment]
# ibus-rime

## 更改ubuntu下ibus-rime的字号、字体、皮肤颜色

需要 gnome-tweak-tool， gnome主题（可以在https://www.gnome-look.org 下载并按照步骤安装）
修改主题的 gnome-shell.css 文件

### 修改字号
打开gnome-shell.css 文件，搜索 .candidate-popup-content 字段（如果没有就新建一个）：
```css
.candidate-popup-content {
       /* 设置字体 */
	font-family: "Microsoft YaHei UI", serif,cantarell,sans-serif;
       /* 设置号 */
	font-size: 15px;
}

.candidate-box {
       /* 设置字体 */
	font-family: "Microsoft YaHei UI", serif,cantarell,sans-serif;
       /* 设置号 */
	font-size: 15px;
}
```

修改后打开gnome-tweak-tool的appearance中shell theme，重新应用这个theme，查看变化，如果shell theme不可选择，则在extensions中打开 user themes即可。

### 修改颜色

```css
.candidate-popup-boxpointer {
  -arrow-border-radius: 1px; 
  -arrow-background-color: #d4d4d4;
  -arrow-border-width: 5px;/*输入法边框*/
  -arrow-border-color: #d4d4d4;
  /*-arrow-border-color: transparent;*/
  -arrow-base: 0;
  -arrow-rise: 0;
  -arrow-box-shadow: none;
  margin: 0.3em 0.8em;
  background-color: #ffffff;
  box-shadow: 0 2px 4px 0 rgba(0, 0, 0, 0.4);
  border-radius: 1px; }

...中间代码省略

.candidate-popup-content {
  padding: 0.4em;
  spacing: 0.1em;/*拼音和汉字的间距*/ 
  font-family: "WenQuanYi Micro Hei", serif,cantarell,sans-serif;
  font-size: 16pt;
  background-color: #eeeeec;
  color: #000000;}

.candidate-box {
  font-family: "WenQuanYi Micro Hei", serif,cantarell,sans-serif;
  font-size: 16pt;
  padding: 0.3em 0.5em 0.3em 0.5em;
  border-radius: 1px;}
  .candidate-box:selected, .candidate-box:hover {
    background-color: #0a3afa;
    color: #ffffff; }
```
对颜色修改，然后应用

修改后的样式如下，选中的标号颜色还不太好

![Screenshot from 2019-04-12 15-16-15](https://user-images.githubusercontent.com/7609775/56019448-32e58d80-5d37-11e9-9f53-3b6a4f6283b3.png)
